### ISSUE TITLE
Build for Flutter SDK 3.27.3

### ISSUE THREAD

**Issue by 2eg01nd** [So00s/Aurora_Fit#13]
The main sdk is available at the link:
https://sdk-repo.omprussia.ru/sdk/flutter/releases/flutter_aurora_3.27.3.tar.gz
After installation, the flutter pub get command will cause errors because some plugin packages are included in the sdk. 
I am attaching the code where there are edits for pubspec.yaml that will fix this problem.
```
name: aurora_fit
description: "This is first fitness app for AuroraOS"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5

  flutter_local_notifications: ^18.0.1
  flutter_local_notifications_aurora:
    git:
      url: https://gitlab.com/omprussia/flutter/flutter-community-plugins/flutter_local_notifications_aurora.git
      ref: aurora-0.5.3
  collection: ^1.16.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  image_picker: ^0.8.7+3

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/full.png
    - assets/images/
    - lib/json/all_workouts.json
    - lib/json/selected_workouts.json

```
